"""Initial migration

Revision ID: c18f88ad2bb7
Revises: 5b473b245874
Create Date: 2025-04-05 23:54:39.701946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18f88ad2bb7'
down_revision: Union[str, None] = '5b473b245874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'created_at')
    op.drop_column('resources', 'created_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('resources', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('bookings', sa.Column('created_at', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
